import pyautogui
import webbrowser
from time import sleep

def log_out():
    pyautogui.click(1151,194, duration = 2)
    sleep(2)
    pyautogui.click(88,623, duration = 3)
    sleep(2)
    pyautogui.click(927,152, duration = 3)
    sleep(2)
    pyautogui.click(651,628, duration = 2)

while True:
    webbrowser.open('https://www.instagram.com/')
    sleep(3)
    pyautogui.click(823,302, duration = 2)
    sleep(2)
    pyautogui.typewrite('hilda.bastos@live.com')
    sleep(1)
    pyautogui.press('tab')
    sleep(1)
    pyautogui.typewrite('**********')
    sleep(2)
    pyautogui.press('tab')
    sleep(1)
    pyautogui.press('tab')
    sleep(1)
    pyautogui.press('space')
    sleep(7)
    pyautogui.click(102,282, duration = 2)
    sleep(2)
    pyautogui.typewrite('Nike')
    sleep(1)
    pyautogui.click(211,297, duration = 2)
    sleep(7)
    pyautogui.moveTo(863,277, duration = 2)
    sleep(1)
    pyautogui.scroll(-400)
    pyautogui.click(456,422, duration = 2)
    sleep(2)
    like = pyautogui.locateCenterOnScreen('like_instagram.PNG')
    sleep(1)
    if like is not None:
        sleep(86400)
    elif like == None:
        pyautogui.click(577,569, duration = 2)
        sleep(2)
        pyautogui.click(616,567, duration = 2)
        sleep(2)
        pyautogui.typewrite('Muito legal!')
        sleep(2)
        pyautogui.click(1020,676, duration = 1)
        sleep(3)
        log_out()
        sleep(86400)